'use client';

import './globals.css';
import style from './layout.module.css';
import { ThemeProvider } from 'next-themes';
import Navbar from '@/components/Navbar';
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NavbarMobile } from '../components/NavbarMobile';
import Bar from '../components/Bar';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className={style.container}>
            <div className="hidden md:block min-h-screen bg-primary-foreground">
              <Navbar />
            </div>
            <div>
              <Bar />
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
